# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/resources/interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1163, 760)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"      background-color: #2c313c;\n"
"      border: 2px solid #3c90a4;  /* Цвет рамки */\n"
"      border-radius: 8px;         /* Закругление углов */\n"
"}\n"
"/* Убираем разделители между виджетами */\n"
"QMainWindow::separator{\n"
"    width: 1px;\n"
"    background-color: #2c313c;\n"
"    /*border: none;*/\n"
"}\n"
"QTabBar::separator{\n"
"    width: 1px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Menu Widget Bar*/\n"
"QMenuBar{\n"
"    background-color: #2c313c;\n"
"    color: white;\n"
"    padding-left: 55px;\n"
"    border: none;\n"
"}\n"
"QMenuBar::item {\n"
"    border-radius:  5px;\n"
"    padding: 5px 5px 5px 5px; /* сверху / справа / снизу / слева*/\n"
"    margin: 5px 3px 5px 0px; /* сверху / справа / снизу / слева*/\n"
"}\n"
"QMenuBar::item::selected{\n"
"    background-color: #505A6E;\n"
"}\n"
"\n"
"/* Menu Inside  */\n"
"QMenu {\n"
"    background-color: #2c313c;\n"
"    border: 0px solid #3c90a4;  /* Добавим тонкую границу для четкости */\n"
"    border-radius: 8px;\n"
"    padding: 4px;  /* Уменьшим общий padding */\n"
"    color: #dedede;\n"
"    font-size: 13px;  /* Чуть уменьшим размер шрифта */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent;\n"
"    padding: 8px 20px 8px 20px;\n"
"    border-radius: 4px;\n"
"    margin: 1px;  /* Минимальный отступ между пунктами */\n"
"    border: none;\n"
"    min-height: 20px;  /* Фиксированная высота пунктов */\n"
"    min-width: 120px;  /* Минимальная ширина меню */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #505A6E;\n"
"    margin: 1px;  /* Убираем увеличение margin при выборе */\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #dedede;  /* Более заметный цвет */\n"
"    margin: 4px 8px;  /* Отступы сверху/снизу и по бокам */\n"
"    border: none;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 10px;           /* Увеличиваем ширину */\n"
"    height: 10px;          /* Увеличиваем высоту */\n"
"    margin-left: 0px;      /* Отступ слева */\n"
"    margin-right: 0px;     /* Отступ справа от галочки */\n"
"    padding: 0px;          /* Внутренний отступ */\n"
"}\n"
"QMenu::indicator:unchecked {\n"
"    image: none;\n"
"}\n"
"/* Отмеченное состояние */\n"
"QMenu::indicator:checked {\n"
"    image: url(:/icons white/icons_white/check.svg);\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Tool Widget */\n"
"QToolBar{\n"
"    background-color: #2c313c;\n"
"    border: none;\n"
"    margin: 0px;\n"
"}\n"
"QToolBar QToolButton{\n"
"    padding: 5px 5px 5px 5px; /* сверху / справа / снизу / слева*/\n"
"    border: none;\n"
"}\n"
"QToolBar QToolButton::hover{\n"
"    background-color: #505A6E;\n"
"    border: none;\n"
"}\n"
"QToolBar QToolButton::checked{\n"
"    background-color: #3c90a4;\n"
"    padding: 5px 5px 5px 4px; /* сверху / справа / снизу / слева*/\n"
"    border-left: 1px solid white;\n"
"    border-right: 0px;\n"
"}\n"
"\n"
"/* Dock Widget */\n"
"QDockWidget QWidget{\n"
"    background :#2c313c;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"QDockWidget{\n"
"    font-size: 15px;\n"
"    color: white;\n"
"    titlebar-close-icon: url(:/icons white/icons_white/x.svg);\n"
"}\n"
"QDockWidget::title{\n"
"    border:2px;\n"
"    border-color: white;\n"
"    background : #2c313c;\n"
"     padding: 5px 0px 5px 25px; /* сверху / справа / снизу / слева*/\n"
"}\n"
"QDockWidget::close-button{\n"
"    image: url(:/icons white/icons_white/x.svg);\n"
"    border-radius: 5px;\n"
"}\n"
"QDockWidget::close-button:hover {\n"
"    border-radius:  5px;\n"
"    background: #505A6E;\n"
"}\n"
"\n"
"/* Tab Widget */\n"
"QTabBar {\n"
"    font-size: 12px;\n"
"    background: #2c313c;\n"
"    border: none;\n"
"    qproperty-drawBase: 0;\n"
"}\n"
"QTabBar::tab {\n"
"    color: white;\n"
"    padding: 5px 12px;\n"
"    border-right: 1px solid;\n"
"    background: #2c313c;\n"
"}\n"
" QTabBar::tab:selected {\n"
"    background: #505A6E;\n"
"    border-bottom: 1px solid white;\n"
" }\n"
"\n"
"\n"
"/* Push Button */\n"
"QDockWidget QPushButton,  QPushButton{\n"
"    text-align:center;\n"
"    padding:5px 11px;\n"
"    border-radius:  5px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 4px;\n"
"    border-color: white;\n"
"    color: white;\n"
"}\n"
"QDockWidget QPushButton::hover{\n"
"    /* background-color: #1f232a; */\n"
"     border-color:  #505A6E;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: #2c313c;\n"
"}\n"
"QDockWidget QPushButton::pressed, QPushButton::checked{\n"
"    background-color:#3c90a4;\n"
"}\n"
"/* QFrame */\n"
"#dockGraphics QFrame{\n"
"    border-radius:  5px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"/* Combo box */\n"
"#dockAnalyse QComboBox{\n"
"    background-color: #2c313c;\n"
"    border-radius:  5px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: white;\n"
"    padding-left:5px;\n"
"    text-align: center;\n"
"}\n"
"#dockAnalyse QComboBox::hover {\n"
"    background-color: #1f232a;\n"
"}\n"
"#dockAnalyse QComboBox::drop-down {\n"
"    border:0;\n"
"}\n"
"#dockAnalyse QComboBox::down-arrow {\n"
"    image:url(:/icons white/icons_white/chevron-down.svg);\n"
"    margin-right: 10%;\n"
"}\n"
"/* Combo box - List View */\n"
"#dockAnalyse QListView{\n"
"     background-color: #2c313c;\n"
"    border-radius:  5px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: white;\n"
"    text-align: center;\n"
"    selection-background-color: #505A6E;\n"
"}\n"
"\n"
"#widgetActions QPushButton, \n"
"#widgetModes QPushButton,  \n"
"#widgetParameters QPushButton, \n"
"#widgetConstants QPushButton{\n"
"    qproperty-icon: url(\" \"); /* empty image */\n"
"    qproperty-iconSize: 20px 20px; /* space for the background image */\n"
"    background-image: url(:/icons white/icons_white/chevron-down.svg);\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding:0px;\n"
"    background-repeat: no-repeat;\n"
"    background-color: transparent;\n"
"}\n"
"#widgetActions QPushButton::hover, \n"
"#widgetModes QPushButton::hover,  \n"
"#widgetParameters QPushButton::hover, \n"
"#widgetConstants QPushButton::hover{\n"
"     background-color: #1f232a;\n"
"}\n"
"#widgetActions QPushButton::checked, \n"
"#widgetModes QPushButton::checked,  \n"
"#widgetParameters QPushButton::checked, \n"
"#widgetConstants QPushButton::checked{\n"
"    background-color: transparent;\n"
"    background-image: url(:/icons white/icons_white/chevron-up.svg);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"#widgetActions QPushButton:checked:hover, \n"
"#widgetModes QPushButton:checked:hover,  \n"
"#widgetParameters QPushButton:checked:hover, \n"
"#widgetConstants QPushButton:checked:hover{\n"
"    background-color: #1f232a;\n"
"    background-image: url(:/icons white/icons_white/chevron-up.svg);\n"
"}\n"
"\n"
"/* Line Edit */\n"
"QLineEdit, #dockAnalyse QLineEdit{\n"
"    text-align:center;\n"
"    background-color:transparent;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 4px;\n"
"    border-color: white;\n"
"    color:white;\n"
"    font: 700 10pt;\n"
"}\n"
"/* Text Edit */\n"
"QTextEdit, #dockAnalyse QTextEdit{\n"
"    background-color:transparent;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 4px;\n"
"    border-color: white;\n"
"    color:white;\n"
"    font: 700 10pt;\n"
"}\n"
"\n"
"/* Other settings */\n"
"#pageHome,#pageAnalyse,#pageReport{\n"
"    color:white;\n"
"    background:#505A6E;\n"
"}\n"
"#pageHome QLabel, #pageAnalyse QLabel,#pageReport QLabel {\n"
"    color: white;\n"
"}\n"
"#centralwidget{\n"
"    background: #2c313c;\n"
"}\n"
"\n"
"QDialog, QImputDialog {\n"
"    border: none;\n"
"    background-color: #1f232a;\n"
"    color: white;\n"
"}")
        self.mainCenterBodyContainer = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setKerning(True)
        self.mainCenterBodyContainer.setFont(font)
        self.mainCenterBodyContainer.setObjectName("mainCenterBodyContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainCenterBodyContainer)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainCenterBodySubContainer = QtWidgets.QWidget(self.mainCenterBodyContainer)
        self.mainCenterBodySubContainer.setObjectName("mainCenterBodySubContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainCenterBodySubContainer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainCenterBodyStacked = QtWidgets.QStackedWidget(self.mainCenterBodySubContainer)
        self.mainCenterBodyStacked.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainCenterBodyStacked.sizePolicy().hasHeightForWidth())
        self.mainCenterBodyStacked.setSizePolicy(sizePolicy)
        self.mainCenterBodyStacked.setObjectName("mainCenterBodyStacked")
        self.pageHome = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageHome.sizePolicy().hasHeightForWidth())
        self.pageHome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pageHome.setFont(font)
        self.pageHome.setObjectName("pageHome")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.pageHome)
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pageHomeContainer = QtWidgets.QWidget(self.pageHome)
        self.pageHomeContainer.setObjectName("pageHomeContainer")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.pageHomeContainer)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.pageHomeSubContainer = QtWidgets.QWidget(self.pageHomeContainer)
        self.pageHomeSubContainer.setObjectName("pageHomeSubContainer")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.pageHomeSubContainer)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(7)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.homeTitle1 = QtWidgets.QLabel(self.pageHomeSubContainer)
        self.homeTitle1.setMaximumSize(QtCore.QSize(500, 150))
        self.homeTitle1.setText("")
        self.homeTitle1.setPixmap(QtGui.QPixmap(":/images/SHV_blue.svg"))
        self.homeTitle1.setScaledContents(False)
        self.homeTitle1.setAlignment(QtCore.Qt.AlignCenter)
        self.homeTitle1.setObjectName("homeTitle1")
        self.verticalLayout_32.addWidget(self.homeTitle1)
        self.homeTitle2 = QtWidgets.QLabel(self.pageHomeSubContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.homeTitle2.setFont(font)
        self.homeTitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.homeTitle2.setObjectName("homeTitle2")
        self.verticalLayout_32.addWidget(self.homeTitle2)
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem)
        self.homeTitle3 = QtWidgets.QLabel(self.pageHomeSubContainer)
        self.homeTitle3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.homeTitle3.setFont(font)
        self.homeTitle3.setObjectName("homeTitle3")
        self.verticalLayout_32.addWidget(self.homeTitle3, 0, QtCore.Qt.AlignLeft)
        self.buttonSelectFile = QtWidgets.QPushButton(self.pageHomeSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSelectFile.sizePolicy().hasHeightForWidth())
        self.buttonSelectFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.buttonSelectFile.setFont(font)
        self.buttonSelectFile.setObjectName("buttonSelectFile")
        self.verticalLayout_32.addWidget(self.buttonSelectFile)
        self.butonRandomData = QtWidgets.QPushButton(self.pageHomeSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butonRandomData.sizePolicy().hasHeightForWidth())
        self.butonRandomData.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.butonRandomData.setFont(font)
        self.butonRandomData.setObjectName("butonRandomData")
        self.verticalLayout_32.addWidget(self.butonRandomData)
        self.verticalLayout_31.addWidget(self.pageHomeSubContainer)
        self.verticalLayout_13.addWidget(self.pageHomeContainer, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mainCenterBodyStacked.addWidget(self.pageHome)
        self.pageAnalyse = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageAnalyse.sizePolicy().hasHeightForWidth())
        self.pageAnalyse.setSizePolicy(sizePolicy)
        self.pageAnalyse.setObjectName("pageAnalyse")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.pageAnalyse)
        self.verticalLayout_14.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pageAnalyseHeader = QtWidgets.QWidget(self.pageAnalyse)
        self.pageAnalyseHeader.setObjectName("pageAnalyseHeader")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pageAnalyseHeader)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pageAnalyseHeaderLable = QtWidgets.QLabel(self.pageAnalyseHeader)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pageAnalyseHeaderLable.setFont(font)
        self.pageAnalyseHeaderLable.setAlignment(QtCore.Qt.AlignCenter)
        self.pageAnalyseHeaderLable.setObjectName("pageAnalyseHeaderLable")
        self.verticalLayout_15.addWidget(self.pageAnalyseHeaderLable)
        self.verticalLayout_14.addWidget(self.pageAnalyseHeader)
        self.pageAnalyseContainer = QtWidgets.QWidget(self.pageAnalyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageAnalyseContainer.sizePolicy().hasHeightForWidth())
        self.pageAnalyseContainer.setSizePolicy(sizePolicy)
        self.pageAnalyseContainer.setObjectName("pageAnalyseContainer")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.pageAnalyseContainer)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pageAnalyseSubContainer = QtWidgets.QWidget(self.pageAnalyseContainer)
        self.pageAnalyseSubContainer.setObjectName("pageAnalyseSubContainer")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.pageAnalyseSubContainer)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(11)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tableDatabase = QtWidgets.QTableWidget(self.pageAnalyseSubContainer)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableDatabase.setFont(font)
        self.tableDatabase.setStyleSheet("")
        self.tableDatabase.setObjectName("tableDatabase")
        self.tableDatabase.setColumnCount(0)
        self.tableDatabase.setRowCount(0)
        self.verticalLayout_25.addWidget(self.tableDatabase)
        self.horizontalLayout_12.addWidget(self.pageAnalyseSubContainer)
        self.verticalLayout_14.addWidget(self.pageAnalyseContainer)
        self.mainCenterBodyStacked.addWidget(self.pageAnalyse)
        self.pageReport = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageReport.sizePolicy().hasHeightForWidth())
        self.pageReport.setSizePolicy(sizePolicy)
        self.pageReport.setObjectName("pageReport")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.pageReport)
        self.verticalLayout_33.setSpacing(7)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.pageReportContainer = QtWidgets.QWidget(self.pageReport)
        self.pageReportContainer.setObjectName("pageReportContainer")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.pageReportContainer)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setSpacing(7)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.reportTitle = QtWidgets.QLabel(self.pageReportContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reportTitle.setFont(font)
        self.reportTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.reportTitle.setObjectName("reportTitle")
        self.verticalLayout_38.addWidget(self.reportTitle)
        self.reportBody = QtWidgets.QFrame(self.pageReportContainer)
        self.reportBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reportBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reportBody.setObjectName("reportBody")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.reportBody)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(7)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.buttonReportCreate = QtWidgets.QPushButton(self.reportBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonReportCreate.sizePolicy().hasHeightForWidth())
        self.buttonReportCreate.setSizePolicy(sizePolicy)
        self.buttonReportCreate.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.buttonReportCreate.setFont(font)
        self.buttonReportCreate.setObjectName("buttonReportCreate")
        self.verticalLayout_34.addWidget(self.buttonReportCreate)
        self.reportText = QtWidgets.QTextEdit(self.reportBody)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.reportText.setFont(font)
        self.reportText.setObjectName("reportText")
        self.verticalLayout_34.addWidget(self.reportText)
        self.verticalLayout_38.addWidget(self.reportBody)
        self.verticalLayout_33.addWidget(self.pageReportContainer)
        self.mainCenterBodyStacked.addWidget(self.pageReport)
        self.verticalLayout_4.addWidget(self.mainCenterBodyStacked)
        self.verticalLayout_3.addWidget(self.mainCenterBodySubContainer)
        MainWindow.setCentralWidget(self.mainCenterBodyContainer)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1163, 41))
        self.menuBar.setObjectName("menuBar")
        self.menuProject = QtWidgets.QMenu(self.menuBar)
        self.menuProject.setObjectName("menuProject")
        self.menuWindow = QtWidgets.QMenu(self.menuBar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(40, 40))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.dockExplorer = QtWidgets.QDockWidget(MainWindow)
        self.dockExplorer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockExplorer.sizePolicy().hasHeightForWidth())
        self.dockExplorer.setSizePolicy(sizePolicy)
        self.dockExplorer.setFloating(False)
        self.dockExplorer.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockExplorer.setObjectName("dockExplorer")
        self.dockExplorerContainer = QtWidgets.QWidget()
        self.dockExplorerContainer.setObjectName("dockExplorerContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockExplorerContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dockExplorerSubContainer = QtWidgets.QWidget(self.dockExplorerContainer)
        self.dockExplorerSubContainer.setObjectName("dockExplorerSubContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockExplorerSubContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.explorerButtons = QtWidgets.QWidget(self.dockExplorerSubContainer)
        self.explorerButtons.setObjectName("explorerButtons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.explorerButtons)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonSelectFolder = QtWidgets.QPushButton(self.explorerButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSelectFolder.setFont(font)
        self.buttonSelectFolder.setObjectName("buttonSelectFolder")
        self.horizontalLayout_5.addWidget(self.buttonSelectFolder)
        self.verticalLayout_2.addWidget(self.explorerButtons)
        self.treeView = QtWidgets.QTreeView(self.dockExplorerSubContainer)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.verticalLayout.addWidget(self.dockExplorerSubContainer)
        self.dockExplorer.setWidget(self.dockExplorerContainer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockExplorer)
        self.dockAnalyse = QtWidgets.QDockWidget(MainWindow)
        self.dockAnalyse.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockAnalyse.sizePolicy().hasHeightForWidth())
        self.dockAnalyse.setSizePolicy(sizePolicy)
        self.dockAnalyse.setMinimumSize(QtCore.QSize(275, 623))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dockAnalyse.setFont(font)
        self.dockAnalyse.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockAnalyse.setObjectName("dockAnalyse")
        self.dockAnalyseContainer = QtWidgets.QWidget()
        self.dockAnalyseContainer.setObjectName("dockAnalyseContainer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dockAnalyseContainer)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.dockAnalyseSubContainer = QtWidgets.QWidget(self.dockAnalyseContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockAnalyseSubContainer.sizePolicy().hasHeightForWidth())
        self.dockAnalyseSubContainer.setSizePolicy(sizePolicy)
        self.dockAnalyseSubContainer.setObjectName("dockAnalyseSubContainer")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.dockAnalyseSubContainer)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widgetActions = QtWidgets.QWidget(self.dockAnalyseSubContainer)
        self.widgetActions.setObjectName("widgetActions")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetActions)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonActions = QtWidgets.QPushButton(self.widgetActions)
        self.pushButtonActions.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons white/icons_white/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonActions.setIcon(icon)
        self.pushButtonActions.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonActions.setCheckable(True)
        self.pushButtonActions.setChecked(True)
        self.pushButtonActions.setObjectName("pushButtonActions")
        self.horizontalLayout.addWidget(self.pushButtonActions, 0, QtCore.Qt.AlignLeft)
        self.labelActions = QtWidgets.QLabel(self.widgetActions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelActions.sizePolicy().hasHeightForWidth())
        self.labelActions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelActions.setFont(font)
        self.labelActions.setObjectName("labelActions")
        self.horizontalLayout.addWidget(self.labelActions)
        self.verticalLayout_16.addWidget(self.widgetActions)
        self.actions = QtWidgets.QFrame(self.dockAnalyseSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actions.sizePolicy().hasHeightForWidth())
        self.actions.setSizePolicy(sizePolicy)
        self.actions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.actions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.actions.setObjectName("actions")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.actions)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.actionsButtonTop = QtWidgets.QWidget(self.actions)
        self.actionsButtonTop.setMaximumSize(QtCore.QSize(16777215, 40))
        self.actionsButtonTop.setObjectName("actionsButtonTop")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.actionsButtonTop)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(7)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.buttonBack = QtWidgets.QPushButton(self.actionsButtonTop)
        self.buttonBack.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons white/icons_white/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonBack.setIcon(icon1)
        self.buttonBack.setIconSize(QtCore.QSize(24, 24))
        self.buttonBack.setObjectName("buttonBack")
        self.horizontalLayout_22.addWidget(self.buttonBack)
        self.buttonForward = QtWidgets.QPushButton(self.actionsButtonTop)
        self.buttonForward.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons white/icons_white/arrow-right-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonForward.setIcon(icon2)
        self.buttonForward.setIconSize(QtCore.QSize(24, 24))
        self.buttonForward.setObjectName("buttonForward")
        self.horizontalLayout_22.addWidget(self.buttonForward)
        self.buttonDelete = QtWidgets.QPushButton(self.actionsButtonTop)
        self.buttonDelete.setEnabled(False)
        self.buttonDelete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons white/icons_white/divide-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDelete.setIcon(icon3)
        self.buttonDelete.setIconSize(QtCore.QSize(24, 24))
        self.buttonDelete.setObjectName("buttonDelete")
        self.horizontalLayout_22.addWidget(self.buttonDelete)
        self.buttonAdd = QtWidgets.QPushButton(self.actionsButtonTop)
        self.buttonAdd.setEnabled(False)
        self.buttonAdd.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons white/icons_white/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAdd.setIcon(icon4)
        self.buttonAdd.setIconSize(QtCore.QSize(24, 24))
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout_22.addWidget(self.buttonAdd)
        self.verticalLayout_5.addWidget(self.actionsButtonTop)
        self.actionsButtonBottom = QtWidgets.QWidget(self.actions)
        self.actionsButtonBottom.setMaximumSize(QtCore.QSize(16777215, 40))
        self.actionsButtonBottom.setObjectName("actionsButtonBottom")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.actionsButtonBottom)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(7)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.buttonClean = QtWidgets.QPushButton(self.actionsButtonBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClean.sizePolicy().hasHeightForWidth())
        self.buttonClean.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonClean.setFont(font)
        self.buttonClean.setStyleSheet("")
        self.buttonClean.setObjectName("buttonClean")
        self.horizontalLayout_23.addWidget(self.buttonClean)
        self.buttonFill = QtWidgets.QPushButton(self.actionsButtonBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFill.sizePolicy().hasHeightForWidth())
        self.buttonFill.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonFill.setFont(font)
        self.buttonFill.setObjectName("buttonFill")
        self.horizontalLayout_23.addWidget(self.buttonFill)
        self.verticalLayout_5.addWidget(self.actionsButtonBottom)
        self.verticalLayout_16.addWidget(self.actions)
        self.widgetModes = QtWidgets.QWidget(self.dockAnalyseSubContainer)
        self.widgetModes.setObjectName("widgetModes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetModes)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonModes = QtWidgets.QPushButton(self.widgetModes)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonModes.setFont(font)
        self.pushButtonModes.setText("")
        self.pushButtonModes.setIcon(icon)
        self.pushButtonModes.setCheckable(True)
        self.pushButtonModes.setChecked(True)
        self.pushButtonModes.setObjectName("pushButtonModes")
        self.horizontalLayout_2.addWidget(self.pushButtonModes, 0, QtCore.Qt.AlignLeft)
        self.labelModes = QtWidgets.QLabel(self.widgetModes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModes.sizePolicy().hasHeightForWidth())
        self.labelModes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelModes.setFont(font)
        self.labelModes.setObjectName("labelModes")
        self.horizontalLayout_2.addWidget(self.labelModes)
        self.verticalLayout_16.addWidget(self.widgetModes)
        self.modes = QtWidgets.QFrame(self.dockAnalyseSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modes.sizePolicy().hasHeightForWidth())
        self.modes.setSizePolicy(sizePolicy)
        self.modes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modes.setObjectName("modes")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.modes)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.modeButtonsTop = QtWidgets.QWidget(self.modes)
        self.modeButtonsTop.setMaximumSize(QtCore.QSize(16777215, 40))
        self.modeButtonsTop.setObjectName("modeButtonsTop")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.modeButtonsTop)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(7)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.buttonBackEleminate = QtWidgets.QPushButton(self.modeButtonsTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBackEleminate.sizePolicy().hasHeightForWidth())
        self.buttonBackEleminate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonBackEleminate.setFont(font)
        self.buttonBackEleminate.setCheckable(True)
        self.buttonBackEleminate.setChecked(True)
        self.buttonBackEleminate.setObjectName("buttonBackEleminate")
        self.horizontalLayout_24.addWidget(self.buttonBackEleminate)
        self.buttonStepwise = QtWidgets.QPushButton(self.modeButtonsTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStepwise.sizePolicy().hasHeightForWidth())
        self.buttonStepwise.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonStepwise.setFont(font)
        self.buttonStepwise.setCheckable(True)
        self.buttonStepwise.setObjectName("buttonStepwise")
        self.horizontalLayout_24.addWidget(self.buttonStepwise)
        self.verticalLayout_9.addWidget(self.modeButtonsTop)
        self.modeButtonsBottom = QtWidgets.QWidget(self.modes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeButtonsBottom.sizePolicy().hasHeightForWidth())
        self.modeButtonsBottom.setSizePolicy(sizePolicy)
        self.modeButtonsBottom.setMaximumSize(QtCore.QSize(16777215, 40))
        self.modeButtonsBottom.setObjectName("modeButtonsBottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.modeButtonsBottom)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonAutoMode = QtWidgets.QPushButton(self.modeButtonsBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAutoMode.sizePolicy().hasHeightForWidth())
        self.buttonAutoMode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonAutoMode.setFont(font)
        self.buttonAutoMode.setText("Авто отбор")
        self.buttonAutoMode.setCheckable(True)
        self.buttonAutoMode.setChecked(True)
        self.buttonAutoMode.setObjectName("buttonAutoMode")
        self.horizontalLayout_3.addWidget(self.buttonAutoMode)
        self.buttonHandMode = QtWidgets.QPushButton(self.modeButtonsBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonHandMode.sizePolicy().hasHeightForWidth())
        self.buttonHandMode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonHandMode.setFont(font)
        self.buttonHandMode.setText("Ручн. отбор")
        self.buttonHandMode.setCheckable(True)
        self.buttonHandMode.setChecked(False)
        self.buttonHandMode.setObjectName("buttonHandMode")
        self.horizontalLayout_3.addWidget(self.buttonHandMode)
        self.verticalLayout_9.addWidget(self.modeButtonsBottom)
        self.modeSelectY = QtWidgets.QFrame(self.modes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeSelectY.sizePolicy().hasHeightForWidth())
        self.modeSelectY.setSizePolicy(sizePolicy)
        self.modeSelectY.setMaximumSize(QtCore.QSize(16777215, 40))
        self.modeSelectY.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modeSelectY.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modeSelectY.setObjectName("modeSelectY")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.modeSelectY)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.countYComboBox = QtWidgets.QComboBox(self.modeSelectY)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countYComboBox.sizePolicy().hasHeightForWidth())
        self.countYComboBox.setSizePolicy(sizePolicy)
        self.countYComboBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.countYComboBox.setFont(font)
        self.countYComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.countYComboBox.setObjectName("countYComboBox")
        self.horizontalLayout_26.addWidget(self.countYComboBox)
        self.choiceYComboBox = QtWidgets.QComboBox(self.modeSelectY)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceYComboBox.sizePolicy().hasHeightForWidth())
        self.choiceYComboBox.setSizePolicy(sizePolicy)
        self.choiceYComboBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.choiceYComboBox.setFont(font)
        self.choiceYComboBox.setObjectName("choiceYComboBox")
        self.horizontalLayout_26.addWidget(self.choiceYComboBox)
        self.verticalLayout_9.addWidget(self.modeSelectY)
        self.verticalLayout_16.addWidget(self.modes)
        self.widgetParameters = QtWidgets.QWidget(self.dockAnalyseSubContainer)
        self.widgetParameters.setObjectName("widgetParameters")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widgetParameters)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonParameters = QtWidgets.QPushButton(self.widgetParameters)
        self.pushButtonParameters.setText("")
        self.pushButtonParameters.setIcon(icon)
        self.pushButtonParameters.setCheckable(True)
        self.pushButtonParameters.setChecked(True)
        self.pushButtonParameters.setObjectName("pushButtonParameters")
        self.horizontalLayout_6.addWidget(self.pushButtonParameters, 0, QtCore.Qt.AlignLeft)
        self.labelParameters = QtWidgets.QLabel(self.widgetParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelParameters.sizePolicy().hasHeightForWidth())
        self.labelParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelParameters.setFont(font)
        self.labelParameters.setObjectName("labelParameters")
        self.horizontalLayout_6.addWidget(self.labelParameters)
        self.verticalLayout_16.addWidget(self.widgetParameters)
        self.parameters = QtWidgets.QFrame(self.dockAnalyseSubContainer)
        self.parameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameters.setObjectName("parameters")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.parameters)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_5 = QtWidgets.QWidget(self.parameters)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.coefficientsLable = QtWidgets.QWidget(self.widget_5)
        self.coefficientsLable.setObjectName("coefficientsLable")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.coefficientsLable)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.labelKK = QtWidgets.QLabel(self.coefficientsLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelKK.setFont(font)
        self.labelKK.setObjectName("labelKK")
        self.verticalLayout_20.addWidget(self.labelKK)
        self.labelKD = QtWidgets.QLabel(self.coefficientsLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelKD.setFont(font)
        self.labelKD.setObjectName("labelKD")
        self.verticalLayout_20.addWidget(self.labelKD)
        self.labelKS = QtWidgets.QLabel(self.coefficientsLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelKS.setFont(font)
        self.labelKS.setObjectName("labelKS")
        self.verticalLayout_20.addWidget(self.labelKS)
        self.verticalLayout_6.addWidget(self.coefficientsLable)
        self.gradeLable = QtWidgets.QWidget(self.widget_5)
        self.gradeLable.setObjectName("gradeLable")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.gradeLable)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.labelOD = QtWidgets.QLabel(self.gradeLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelOD.setFont(font)
        self.labelOD.setObjectName("labelOD")
        self.verticalLayout_27.addWidget(self.labelOD)
        self.labelNOD = QtWidgets.QLabel(self.gradeLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNOD.setFont(font)
        self.labelNOD.setObjectName("labelNOD")
        self.verticalLayout_27.addWidget(self.labelNOD)
        self.labelOSKO = QtWidgets.QLabel(self.gradeLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelOSKO.setFont(font)
        self.labelOSKO.setObjectName("labelOSKO")
        self.verticalLayout_27.addWidget(self.labelOSKO)
        self.verticalLayout_6.addWidget(self.gradeLable)
        self.horizontalLayout_8.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.parameters)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.coefficientsEdit = QtWidgets.QWidget(self.widget_6)
        self.coefficientsEdit.setObjectName("coefficientsEdit")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.coefficientsEdit)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.lineEditKK = QtWidgets.QLineEdit(self.coefficientsEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditKK.sizePolicy().hasHeightForWidth())
        self.lineEditKK.setSizePolicy(sizePolicy)
        self.lineEditKK.setReadOnly(True)
        self.lineEditKK.setObjectName("lineEditKK")
        self.verticalLayout_26.addWidget(self.lineEditKK)
        self.lineEditKD = QtWidgets.QLineEdit(self.coefficientsEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditKD.sizePolicy().hasHeightForWidth())
        self.lineEditKD.setSizePolicy(sizePolicy)
        self.lineEditKD.setReadOnly(True)
        self.lineEditKD.setObjectName("lineEditKD")
        self.verticalLayout_26.addWidget(self.lineEditKD)
        self.lineEditKS = QtWidgets.QLineEdit(self.coefficientsEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditKS.sizePolicy().hasHeightForWidth())
        self.lineEditKS.setSizePolicy(sizePolicy)
        self.lineEditKS.setReadOnly(True)
        self.lineEditKS.setObjectName("lineEditKS")
        self.verticalLayout_26.addWidget(self.lineEditKS)
        self.verticalLayout_7.addWidget(self.coefficientsEdit)
        self.gradeEdit = QtWidgets.QWidget(self.widget_6)
        self.gradeEdit.setObjectName("gradeEdit")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.gradeEdit)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.lineEditOD = QtWidgets.QLineEdit(self.gradeEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOD.sizePolicy().hasHeightForWidth())
        self.lineEditOD.setSizePolicy(sizePolicy)
        self.lineEditOD.setReadOnly(True)
        self.lineEditOD.setObjectName("lineEditOD")
        self.verticalLayout_28.addWidget(self.lineEditOD)
        self.lineEditNOD = QtWidgets.QLineEdit(self.gradeEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNOD.sizePolicy().hasHeightForWidth())
        self.lineEditNOD.setSizePolicy(sizePolicy)
        self.lineEditNOD.setReadOnly(True)
        self.lineEditNOD.setObjectName("lineEditNOD")
        self.verticalLayout_28.addWidget(self.lineEditNOD)
        self.lineEditOSKO = QtWidgets.QLineEdit(self.gradeEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOSKO.sizePolicy().hasHeightForWidth())
        self.lineEditOSKO.setSizePolicy(sizePolicy)
        self.lineEditOSKO.setReadOnly(True)
        self.lineEditOSKO.setObjectName("lineEditOSKO")
        self.verticalLayout_28.addWidget(self.lineEditOSKO)
        self.verticalLayout_7.addWidget(self.gradeEdit)
        self.horizontalLayout_8.addWidget(self.widget_6)
        self.verticalLayout_16.addWidget(self.parameters)
        self.widgetConstants = QtWidgets.QWidget(self.dockAnalyseSubContainer)
        self.widgetConstants.setObjectName("widgetConstants")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widgetConstants)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonConstants = QtWidgets.QPushButton(self.widgetConstants)
        self.pushButtonConstants.setText("")
        self.pushButtonConstants.setIcon(icon)
        self.pushButtonConstants.setCheckable(True)
        self.pushButtonConstants.setChecked(True)
        self.pushButtonConstants.setObjectName("pushButtonConstants")
        self.horizontalLayout_7.addWidget(self.pushButtonConstants, 0, QtCore.Qt.AlignLeft)
        self.labelConstants = QtWidgets.QLabel(self.widgetConstants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelConstants.sizePolicy().hasHeightForWidth())
        self.labelConstants.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelConstants.setFont(font)
        self.labelConstants.setObjectName("labelConstants")
        self.horizontalLayout_7.addWidget(self.labelConstants)
        self.verticalLayout_16.addWidget(self.widgetConstants)
        self.constParameters = QtWidgets.QFrame(self.dockAnalyseSubContainer)
        self.constParameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.constParameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.constParameters.setObjectName("constParameters")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.constParameters)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.constValues = QtWidgets.QFrame(self.constParameters)
        self.constValues.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.constValues.setFrameShadow(QtWidgets.QFrame.Raised)
        self.constValues.setObjectName("constValues")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.constValues)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.constLable = QtWidgets.QWidget(self.constValues)
        self.constLable.setObjectName("constLable")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.constLable)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.labelKSConst = QtWidgets.QLabel(self.constLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelKSConst.setFont(font)
        self.labelKSConst.setObjectName("labelKSConst")
        self.verticalLayout_29.addWidget(self.labelKSConst)
        self.labelKDConst = QtWidgets.QLabel(self.constLable)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelKDConst.setFont(font)
        self.labelKDConst.setObjectName("labelKDConst")
        self.verticalLayout_29.addWidget(self.labelKDConst)
        self.horizontalLayout_15.addWidget(self.constLable, 0, QtCore.Qt.AlignLeft)
        self.constEdit = QtWidgets.QWidget(self.constValues)
        self.constEdit.setObjectName("constEdit")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.constEdit)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.lineEditKSConst = QtWidgets.QLineEdit(self.constEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditKSConst.sizePolicy().hasHeightForWidth())
        self.lineEditKSConst.setSizePolicy(sizePolicy)
        self.lineEditKSConst.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditKSConst.setObjectName("lineEditKSConst")
        self.verticalLayout_30.addWidget(self.lineEditKSConst)
        self.lineEditKDConst = QtWidgets.QLineEdit(self.constEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditKDConst.sizePolicy().hasHeightForWidth())
        self.lineEditKDConst.setSizePolicy(sizePolicy)
        self.lineEditKDConst.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditKDConst.setObjectName("lineEditKDConst")
        self.verticalLayout_30.addWidget(self.lineEditKDConst)
        self.horizontalLayout_15.addWidget(self.constEdit)
        self.verticalLayout_10.addWidget(self.constValues)
        self.verticalLayout_16.addWidget(self.constParameters)
        self.verticalLayout_8.addWidget(self.dockAnalyseSubContainer, 0, QtCore.Qt.AlignTop)
        self.dockAnalyse.setWidget(self.dockAnalyseContainer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockAnalyse)
        self.dockGraphics = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockGraphics.sizePolicy().hasHeightForWidth())
        self.dockGraphics.setSizePolicy(sizePolicy)
        self.dockGraphics.setMinimumSize(QtCore.QSize(250, 150))
        self.dockGraphics.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockGraphics.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockGraphics.setObjectName("dockGraphics")
        self.dockGraphicsContainer = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockGraphicsContainer.sizePolicy().hasHeightForWidth())
        self.dockGraphicsContainer.setSizePolicy(sizePolicy)
        self.dockGraphicsContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.dockGraphicsContainer.setObjectName("dockGraphicsContainer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.dockGraphicsContainer)
        self.verticalLayout_12.setContentsMargins(11, 0, 11, 11)
        self.verticalLayout_12.setSpacing(11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.dockGraphicsSubContainer = QtWidgets.QWidget(self.dockGraphicsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockGraphicsSubContainer.sizePolicy().hasHeightForWidth())
        self.dockGraphicsSubContainer.setSizePolicy(sizePolicy)
        self.dockGraphicsSubContainer.setObjectName("dockGraphicsSubContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.dockGraphicsSubContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.GraphicsButtons = QtWidgets.QWidget(self.dockGraphicsSubContainer)
        self.GraphicsButtons.setMinimumSize(QtCore.QSize(0, 0))
        self.GraphicsButtons.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.GraphicsButtons.setSizeIncrement(QtCore.QSize(2, 0))
        self.GraphicsButtons.setObjectName("GraphicsButtons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.GraphicsButtons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonGrSKD = QtWidgets.QPushButton(self.GraphicsButtons)
        self.buttonGrSKD.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonGrSKD.setFont(font)
        self.buttonGrSKD.setCheckable(True)
        self.buttonGrSKD.setChecked(True)
        self.buttonGrSKD.setObjectName("buttonGrSKD")
        self.horizontalLayout_4.addWidget(self.buttonGrSKD)
        self.buttonGrSKS = QtWidgets.QPushButton(self.GraphicsButtons)
        self.buttonGrSKS.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonGrSKS.setFont(font)
        self.buttonGrSKS.setCheckable(True)
        self.buttonGrSKS.setChecked(False)
        self.buttonGrSKS.setObjectName("buttonGrSKS")
        self.horizontalLayout_4.addWidget(self.buttonGrSKS)
        self.buttonGrE = QtWidgets.QPushButton(self.GraphicsButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGrE.sizePolicy().hasHeightForWidth())
        self.buttonGrE.setSizePolicy(sizePolicy)
        self.buttonGrE.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonGrE.setFont(font)
        self.buttonGrE.setCheckable(True)
        self.buttonGrE.setObjectName("buttonGrE")
        self.horizontalLayout_4.addWidget(self.buttonGrE)
        self.verticalLayout_11.addWidget(self.GraphicsButtons)
        self.verticalLayout_12.addWidget(self.dockGraphicsSubContainer, 0, QtCore.Qt.AlignTop)
        self.Graphics = QtWidgets.QFrame(self.dockGraphicsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Graphics.sizePolicy().hasHeightForWidth())
        self.Graphics.setSizePolicy(sizePolicy)
        self.Graphics.setMinimumSize(QtCore.QSize(0, 0))
        self.Graphics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Graphics.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Graphics.setObjectName("Graphics")
        self.verticalLayout_12.addWidget(self.Graphics)
        self.dockGraphics.setWidget(self.dockGraphicsContainer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockGraphics)
        self.actionOpenFolderMB = QtWidgets.QAction(MainWindow)
        self.actionOpenFolderMB.setObjectName("actionOpenFolderMB")
        self.actionOpenFileMB = QtWidgets.QAction(MainWindow)
        self.actionOpenFileMB.setObjectName("actionOpenFileMB")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actioninterface_ui = QtWidgets.QAction(MainWindow)
        self.actioninterface_ui.setObjectName("actioninterface_ui")
        self.actionnew_ui = QtWidgets.QAction(MainWindow)
        self.actionnew_ui.setObjectName("actionnew_ui")
        self.actionAnalyseTB = QtWidgets.QAction(MainWindow)
        self.actionAnalyseTB.setCheckable(True)
        self.actionAnalyseTB.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons white/icons_white/layers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyseTB.setIcon(icon5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionAnalyseTB.setFont(font)
        self.actionAnalyseTB.setVisible(True)
        self.actionAnalyseTB.setObjectName("actionAnalyseTB")
        self.actionHomeTB = QtWidgets.QAction(MainWindow)
        self.actionHomeTB.setCheckable(True)
        self.actionHomeTB.setChecked(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons white/icons_white/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHomeTB.setIcon(icon6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionHomeTB.setFont(font)
        self.actionHomeTB.setShortcutVisibleInContextMenu(False)
        self.actionHomeTB.setObjectName("actionHomeTB")
        self.actionReportTB = QtWidgets.QAction(MainWindow)
        self.actionReportTB.setCheckable(True)
        self.actionReportTB.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons white/icons_white/clipboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReportTB.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionReportTB.setFont(font)
        self.actionReportTB.setVisible(True)
        self.actionReportTB.setObjectName("actionReportTB")
        self.actionConsoleTB = QtWidgets.QAction(MainWindow)
        self.actionConsoleTB.setCheckable(False)
        self.actionConsoleTB.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons white/icons_white/terminal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConsoleTB.setIcon(icon8)
        self.actionConsoleTB.setVisible(False)
        self.actionConsoleTB.setIconVisibleInMenu(True)
        self.actionConsoleTB.setObjectName("actionConsoleTB")
        self.actionNewProjectMB = QtWidgets.QAction(MainWindow)
        self.actionNewProjectMB.setObjectName("actionNewProjectMB")
        self.actionTreeTB = QtWidgets.QAction(MainWindow)
        self.actionTreeTB.setCheckable(False)
        self.actionTreeTB.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons white/icons_white/type.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTreeTB.setIcon(icon9)
        self.actionTreeTB.setVisible(False)
        self.actionTreeTB.setShortcutVisibleInContextMenu(True)
        self.actionTreeTB.setObjectName("actionTreeTB")
        self.actionGraphicsTB = QtWidgets.QAction(MainWindow)
        self.actionGraphicsTB.setCheckable(False)
        self.actionGraphicsTB.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons white/icons_white/image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGraphicsTB.setIcon(icon10)
        self.actionGraphicsTB.setVisible(False)
        self.actionGraphicsTB.setIconVisibleInMenu(True)
        self.actionGraphicsTB.setObjectName("actionGraphicsTB")
        self.actionAnalyseMB = QtWidgets.QAction(MainWindow)
        self.actionAnalyseMB.setCheckable(True)
        self.actionAnalyseMB.setEnabled(True)
        self.actionAnalyseMB.setObjectName("actionAnalyseMB")
        self.actionExplorerMB = QtWidgets.QAction(MainWindow)
        self.actionExplorerMB.setCheckable(True)
        self.actionExplorerMB.setChecked(False)
        self.actionExplorerMB.setEnabled(True)
        self.actionExplorerMB.setVisible(True)
        self.actionExplorerMB.setObjectName("actionExplorerMB")
        self.actionGraphicsMB = QtWidgets.QAction(MainWindow)
        self.actionGraphicsMB.setCheckable(True)
        self.actionGraphicsMB.setEnabled(True)
        self.actionGraphicsMB.setObjectName("actionGraphicsMB")
        self.actionConsoleMB = QtWidgets.QAction(MainWindow)
        self.actionConsoleMB.setCheckable(True)
        self.actionConsoleMB.setEnabled(True)
        self.actionConsoleMB.setObjectName("actionConsoleMB")
        self.actionHelpMB = QtWidgets.QAction(MainWindow)
        self.actionHelpMB.setText("")
        self.actionHelpMB.setIconText("")
        self.actionHelpMB.setToolTip("")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionHelpMB.setFont(font)
        self.actionHelpMB.setObjectName("actionHelpMB")
        self.actionInstructionMB = QtWidgets.QAction(MainWindow)
        self.actionInstructionMB.setObjectName("actionInstructionMB")
        self.menuProject.addAction(self.actionOpenFolderMB)
        self.menuProject.addAction(self.actionOpenFileMB)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionSave)
        self.menuWindow.addAction(self.actionExplorerMB)
        self.menuWindow.addAction(self.actionAnalyseMB)
        self.menuWindow.addAction(self.actionGraphicsMB)
        self.menuHelp.addAction(self.actionInstructionMB)
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionHomeTB)
        self.toolBar.addAction(self.actionAnalyseTB)
        self.toolBar.addAction(self.actionReportTB)
        self.toolBar.addAction(self.actionGraphicsTB)
        self.toolBar.addAction(self.actionConsoleTB)
        self.toolBar.addAction(self.actionTreeTB)

        self.retranslateUi(MainWindow)
        self.mainCenterBodyStacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeTitle2.setText(_translate("MainWindow", "МНОЖЕСТВЕННАЯ РЕГРЕССИЯ\n"
"BY ARTEM SHISHOV"))
        self.homeTitle3.setText(_translate("MainWindow", "Выберите источник данных для анализа:"))
        self.buttonSelectFile.setToolTip(_translate("MainWindow", "Файл для анализа"))
        self.buttonSelectFile.setText(_translate("MainWindow", "ФАЙЛ"))
        self.butonRandomData.setToolTip(_translate("MainWindow", "Генерация случайных данных"))
        self.butonRandomData.setText(_translate("MainWindow", "СЛУЧАЙНЫЕ ДАННЫЕ"))
        self.pageAnalyseHeaderLable.setText(_translate("MainWindow", "Анализ данных"))
        self.reportTitle.setText(_translate("MainWindow", "Отчет"))
        self.buttonReportCreate.setToolTip(_translate("MainWindow", "Кликните для создания отчета"))
        self.buttonReportCreate.setText(_translate("MainWindow", "Создать Отчет"))
        self.reportText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:696; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt; font-weight:400;\"><br /></p></body></html>"))
        self.menuProject.setTitle(_translate("MainWindow", "Файл"))
        self.menuWindow.setTitle(_translate("MainWindow", "Окно"))
        self.menuHelp.setTitle(_translate("MainWindow", "Справка"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockExplorer.setWindowTitle(_translate("MainWindow", "ПРОВОДНИК"))
        self.buttonSelectFolder.setText(_translate("MainWindow", "Выберите папку"))
        self.dockAnalyse.setWindowTitle(_translate("MainWindow", "АНАЛИЗ"))
        self.labelActions.setText(_translate("MainWindow", "Действия"))
        self.buttonBack.setToolTip(_translate("MainWindow", "Шаг обратно"))
        self.buttonForward.setToolTip(_translate("MainWindow", "Шаг вперед"))
        self.buttonDelete.setToolTip(_translate("MainWindow", "Удалить Х"))
        self.buttonAdd.setToolTip(_translate("MainWindow", "Добавить Х"))
        self.buttonClean.setToolTip(_translate("MainWindow", "Очистить таблицу"))
        self.buttonClean.setText(_translate("MainWindow", "Очистить"))
        self.buttonFill.setToolTip(_translate("MainWindow", "Заполнить таблицу"))
        self.buttonFill.setText(_translate("MainWindow", "Заполнить"))
        self.labelModes.setText(_translate("MainWindow", "Режимы"))
        self.buttonBackEleminate.setToolTip(_translate("MainWindow", "Обратная ликвидация"))
        self.buttonBackEleminate.setText(_translate("MainWindow", "ОЛ"))
        self.buttonStepwise.setToolTip(_translate("MainWindow", "Прямое включение"))
        self.buttonStepwise.setText(_translate("MainWindow", "ПВ"))
        self.buttonAutoMode.setToolTip(_translate("MainWindow", "Автоматический отбор переменных"))
        self.buttonHandMode.setToolTip(_translate("MainWindow", "Ручной отбор переменных"))
        self.countYComboBox.setToolTip(_translate("MainWindow", "Количество зависимых переменных"))
        self.choiceYComboBox.setToolTip(_translate("MainWindow", "Зависимые переменные"))
        self.labelParameters.setText(_translate("MainWindow", "Параметры"))
        self.labelKK.setToolTip(_translate("MainWindow", "Коэффициент Корреляции"))
        self.labelKK.setText(_translate("MainWindow", "КК    "))
        self.labelKD.setToolTip(_translate("MainWindow", "Коэффициент Детерминации"))
        self.labelKD.setText(_translate("MainWindow", "КД"))
        self.labelKS.setToolTip(_translate("MainWindow", "Коэффициент Статистики"))
        self.labelKS.setText(_translate("MainWindow", "КС"))
        self.labelOD.setToolTip(_translate("MainWindow", "Оценка Дисперсии"))
        self.labelOD.setText(_translate("MainWindow", "ОД"))
        self.labelNOD.setToolTip(_translate("MainWindow", "Несмещенная Оценка Дисперсии"))
        self.labelNOD.setText(_translate("MainWindow", "НОД"))
        self.labelOSKO.setToolTip(_translate("MainWindow", "Оценка Среднеквадратичного Отклонения"))
        self.labelOSKO.setText(_translate("MainWindow", "ОСКО"))
        self.labelConstants.setText(_translate("MainWindow", "Критерии"))
        self.labelKSConst.setToolTip(_translate("MainWindow", "Константа Коэффициента Статистики"))
        self.labelKSConst.setText(_translate("MainWindow", "КС Const"))
        self.labelKDConst.setToolTip(_translate("MainWindow", "Константа Коэффициента Детерминации"))
        self.labelKDConst.setText(_translate("MainWindow", "КД Const"))
        self.dockGraphics.setWindowTitle(_translate("MainWindow", "ГРАФИКИ"))
        self.buttonGrSKD.setToolTip(_translate("MainWindow", "Значения КД обратной ликвидации"))
        self.buttonGrSKD.setText(_translate("MainWindow", "КД"))
        self.buttonGrSKS.setToolTip(_translate("MainWindow", "Значения КС прямого включения"))
        self.buttonGrSKS.setText(_translate("MainWindow", "КC"))
        self.buttonGrE.setToolTip(_translate("MainWindow", "Ошибки соответствия посчитанного и начального Y"))
        self.buttonGrE.setText(_translate("MainWindow", "Yисх ~ Yрас"))
        self.actionOpenFolderMB.setText(_translate("MainWindow", "Открыть папку"))
        self.actionOpenFileMB.setText(_translate("MainWindow", "Открыть файл"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionSave_As.setText(_translate("MainWindow", "Сохранить как..."))
        self.actioninterface_ui.setText(_translate("MainWindow", "interface.ui"))
        self.actionnew_ui.setText(_translate("MainWindow", "new.ui"))
        self.actionAnalyseTB.setText(_translate("MainWindow", "Анализ"))
        self.actionAnalyseTB.setToolTip(_translate("MainWindow", "Анализ"))
        self.actionAnalyseTB.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionHomeTB.setText(_translate("MainWindow", "Проводник"))
        self.actionHomeTB.setToolTip(_translate("MainWindow", "Проводник"))
        self.actionHomeTB.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionReportTB.setText(_translate("MainWindow", "Отчет"))
        self.actionReportTB.setToolTip(_translate("MainWindow", "Отчет"))
        self.actionReportTB.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionConsoleTB.setText(_translate("MainWindow", "Консоль"))
        self.actionConsoleTB.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionNewProjectMB.setText(_translate("MainWindow", "Новый проект"))
        self.actionTreeTB.setText(_translate("MainWindow", "Дерево"))
        self.actionTreeTB.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionGraphicsTB.setText(_translate("MainWindow", "Графики"))
        self.actionGraphicsTB.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionAnalyseMB.setText(_translate("MainWindow", "Анализ"))
        self.actionExplorerMB.setText(_translate("MainWindow", "Проводник"))
        self.actionGraphicsMB.setText(_translate("MainWindow", "Графики"))
        self.actionConsoleMB.setText(_translate("MainWindow", "Консоль"))
        self.actionInstructionMB.setText(_translate("MainWindow", "Инструкция"))
import ui.resources as resources
